config/routes.rb
Stirs::Application.routes.draw do

  devise_for :users

  resources :users, only: [:show,:update, :index] do
  
    resources :quotes, only: [:index, :new, :create, :destroy]
    resources :current_quotes, only: [:update]
    resources :cards, only: [:new, :create, :index, :destroy]

    resources :friendships, only: [:create, :destroy, :index, :update] do
      collection do
        post 'invite'
      end
    end

    resources :shelves do 

      resources :items do
        resources :feelings
      end      
    end

    resources :feelings

  end

  resources :shelves do
    resources :items
  end
  root to: 'static_pages#home'

  resources :items

end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id         :integer          not null, primary key
#  author     :string(255)
#  body       :text(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Quote < ActiveRecord::Base
  attr_accessible :author, :body

  belongs_to :user

  validates :body, presence: true
  validates :user_id, presence: true


  def to_string
  	out = "\"#{self.body}\""
  	out << " - #{self.author}" if self.author and !self.author.empty?
  	out
  end

  # before_destroy do
  # 	if self.id == self.user.current_quote_id
  #     errors.add(:id)
  #     false
  #   end
  # end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def new
  end

  def create
    @user = current_user
    @quote = current_user.quotes.build(params[:quote])
    if @quote.save
      flash[:success] = "New Quote created"
      redirect_to user_quotes_path(current_user)
    else
      @quotes = current_user.quotes.all
      render action: "index"
    end    
  end

  def edit


  end

  def destroy
    @quote = current_user.quotes.find(params[:id])
    if @quote.destroy
      flash[:success] = "Quote destroyed"
    else
      flash[:failure] = "Cannot destroy current quote"
    end if
    redirect_to user_quotes_path(current_user)
  end

  def index
  	@user = User.find(params[:user_id])
    @quotes = @user.quotes.all
    @quote = @user.quotes.build
  end

end

app/views/quotes/_quote.html.erb
<li>

<%# quote.to_string  %>

<blockquote>
	<p> "<%= quote.body%>" </p>
	<small class = "pull-right"><%= quote.author%></small>
</blockquote>	
<% if @user == current_user %>
	<div align="right">
		<br>
		<%= link_to "Delete", [current_user, quote] , method: :delete, data: { confirm: "You sure?" } %>
		<br>
		<%= link_to "Make current", user_current_quote_path(current_user, quote), method: :put %>
	</div>
<% end %>

</li>

app/views/quotes/index.html.erb
<%= render 'shared/userhead' %>

<div class="row">
<% if @user == current_user %>
	<div class="span8">
<% else %>
	<div class="span12 ">
<% end %>
<div class = "reads">
	<h5> All Quotes </h5>
	<% if @quotes.any? %>
		<ul class = "reads">
			<%= render @quotes %>
		</ul>
	<% else %>
	No Quotes added yet
	<% end %>
	</div>
	</div>
	<% if @user == current_user %>
		<div class="span4 ">

			<%= form_for [@user, @quote] do |f| %>
			 	<%= render 'shared/error_messages', object: f.object %>
			 	<div><%= f.hidden_field :id %></div>
			 	<div class = "pull-right">
			    <div class = "field">
				  	<%= f.label :body %>		
			      	<%= f.text_area :body %>
				  	<%= f.label :author %>		
			      	<%= f.text_field :author %>      	
			    </div>
			    <%= f.submit "Add", class: "btn btn-large btn-primary pull-right" %>
			    </div>
			<% end %>		
		</div>
	<% end %>	
</div>