config/routes.rb
Stirs::Application.routes.draw do

  devise_for :users

  resources :users, only: [:show,:update, :index] do
  
    resources :quotes, only: [:index, :new, :create, :destroy]
    resources :current_quotes, only: [:update]
    resources :cards, only: [:new, :create, :index, :destroy]

    resources :friendships, only: [:create, :destroy, :index, :update] do
      collection do
        post 'invite'
      end
    end

    resources :shelves do 

      resources :items do
        resources :feelings
      end      
    end

    resources :feelings

  end

  resources :shelves do
    resources :items
  end
  root to: 'static_pages#home'

  resources :items

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_shelves_sidebar.html.erb
<div class="span3 ">
	<ul class="nav nav-tabs nav-stacked">
		<% if @shelves.any? %>
			<%= render @shelves %>
			<%= link_to "Add Shelf", new_user_shelf_path(current_user), class: "pull-right" if @user == current_user && !current_page?(new_user_shelf_path(@user)) %>
		<% else %>
			No Shelves created yet
		<% end %>
	</ul>

</div>

app/views/shared/_userhead.html.erb
<h2><%=  link_to "#{@user.name}(#{@user.username})", user_path(@user) %></h2>

<% if user_signed_in? && @user != current_user && !current_user.friendships.exists?(friend_id: @user.id) %>
	<%= link_to "Send friend request", user_friendships_path(friend_id: @user.id), method: "post", disable_with: "Requesting..." %>
<% end %>

<%# if current_user.friends.exists?(@user.id) %>
	<%# link_to "Send Card", new_user_card_path(receiver_id: @user.id) %>
<%# end %>

<% if @user.quotes.any? %>
	<% if @user.current_quote %>
	<blockquote>
		<p> "<%= @user.current_quote.body%>" </p>
		<small class = "pull-right"><%= @user.current_quote.author%></small>
	</blockquote>	
	<% end %>
	
	<div class = "pull-right">
	<% if current_page?(user_quotes_path(@user)) %>	
      <%= link_to "Back to shelves", user_shelves_path(@user) %>
    <% else %>
		<% if @user == current_user %>
				<%= link_to "Edit quotes", user_quotes_path(@user) %>
		<% else %>
				<%= link_to "All User Quotes",  user_quotes_path(@user) if @user.quotes.any? %>
		<% end %>	
	<% end %>
	</div>
<% else %>
<%= link_to "Add Quote", user_quotes_path(@user) if @user == current_user %>
<% end %>
<br>
<br>