config/routes.rb
Stirs::Application.routes.draw do

  devise_for :users

  resources :users, only: [:show,:update, :index] do
  
    resources :quotes, only: [:index, :new, :create, :destroy]
    resources :current_quotes, only: [:update]
    resources :cards, only: [:new, :create, :index, :destroy]

    resources :friendships, only: [:create, :destroy, :index, :update] do
      collection do
        post 'invite'
      end
    end

    resources :shelves do 

      resources :items do
        resources :feelings
      end      
    end

    resources :feelings

  end

  resources :shelves do
    resources :items
  end
  root to: 'static_pages#home'

  resources :items

end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  friend_id  :integer
#  status     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Friendship < ActiveRecord::Base
  attr_accessible :status,:friend_id

  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def index
		puts "the current user is #{current_user.class}"
		if !current_user
			session[:target] = 'friendships'
			redirect_to new_user_session_path
			return false
		end
		@user = current_user

	  @friendships_pend = @user.friendships.where(status: 'pending')
		@friendships_req = @user.friendships.where(status: 'requested')
		@friendships_conf = @user.friendships.where(status: 'confirmed')

		@friends = @user.friends
	end	


  def create
	  @friend = User.find(params[:friend_id])
	  if current_user.request_friend(@friend)
	  	puts 'requesting friendship'
	  	FriendMailer.friend_request_email(current_user, @friend).deliver
	    flash.keep[:notice] = "Friendship Requested"
	    redirect_to user_path(@friend)
	  else
	    flash.keep[:error] = "Could not Request"
	    redirect_to user_path(@friend)
	  end  	
  end

	def update
		@friend = User.find(params[:friend_id])
		if current_user.confirm_friend(@friend)
			flash[:success] = "Friend Confirmed"
		else
			flash[:error] = "Could not confirm friend"
		end
		redirect_to user_friendships_path(current_user)
	end

  def destroy
	  @friendship = current_user.friendships.find(params[:id])
	  @inverse = current_user.inverse_friendships.where(user_id: @friendship.friend_id).first
	  @friendship.destroy
	  @inverse.destroy
	  flash[:notice] = "Removed friendship."
	  redirect_to user_friendships_path(current_user)
  end

  def invite
  	friend_email = params[:friend_email]
  	if FriendMailer.invite_email(current_user, friend_email).deliver
  		flash[:notice] = "Friend invited #{friend_email}"
  	end
  	redirect_to user_friendships_path(current_user)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<%= render 'shared/userhead' %>
<div class="container">
	<%#= link_to 'Invite Friend' controller: 'friendships', action: 'invite' %>	
	<div class="row">
		<div class="span9">
		  <% if @friendships_conf.any? %>	
		      
		      	<ul class = "reads">
				  	<% @friendships_conf.each do |conf| %>
				  	<li class = "reads">
				  		<%= link_to conf.friend.name, user_path(conf.friend) %>	 
				  		(<%= link_to "Defriend", [current_user, conf] , method: :delete, data: { confirm: "Defriend #{conf.friend.name}?" } %>)	
				  	</li>
				  	<% end %>
			  		<ul class = "reads">
			  
		  <% end %>
		</div>
		<div class="span3">
		  <% if @friendships_pend.any? %>
			  	<h5> Received Friend Requests </h5>
			  	    <% @friendships_pend.each do |pend| %>
				  	<li class = "reads">
				  		<%= link_to pend.friend.name, user_path(pend.friend) %>
				  		(<%= link_to "Confirm Friend", user_friendship_path(current_user, pend, friend_id: pend.friend), method: "put" %>)
				  	</li>
				  	<% end %>
		  <% end %>

		  <% if @friendships_req.any? %>
			  	<h5> Sent Friend Requests (Waiting) </h5>
			  	    <% @friendships_req.each do |req| %>
				  	<li class = "reads">
				  		<%= link_to req.friend.name, user_path(req.friend) %>
				  	</li>
				  	<% end %>
			  
		  <% end %>	  
			<h5> Invite Friend </h5>
			<%= form_tag invite_user_friendships_path do %>
			  <%= label_tag(:friend_email, "Friends email") %>
			  <%= text_field_tag(:friend_email) %>
			  <%= submit_tag("Invite") %>
			<% end %>
		</div>



	</div> 
</div> 