config/routes.rb
Stirs::Application.routes.draw do

  devise_for :users

  resources :users, only: [:show,:update, :index] do
  
    resources :quotes, only: [:index, :new, :create, :destroy]
    resources :current_quotes, only: [:update]
    resources :cards, only: [:new, :create, :index, :destroy]

    resources :friendships, only: [:create, :destroy, :index, :update] do
      collection do
        post 'invite'
      end
    end

    resources :shelves do 

      resources :items do
        resources :feelings
      end      
    end

    resources :feelings

  end

  resources :shelves do
    resources :items
  end
  root to: 'static_pages#home'

  resources :items

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <%#= link_to "SoulStirs", root_path, id: "logo" %>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Stirs</a>
    </div>
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav pull-right navbar-collapse">

          <% if !user_signed_in? %>  
            <li><%= link_to 'Home', root_path %></li>         
          <% else %>  
            <li><%= link_to "Shelves", user_shelves_path(current_user) %></li>    
            <li><%= link_to 'Cards', user_cards_path(current_user) %></li>
          <% end %> 

          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Users <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">          
              <li><%= link_to 'Friends', user_friendships_path(current_user) if user_signed_in? %></li>
              <li><%= link_to 'Search all Users', users_path %></li>
            </ul> 
          </li>  

          <% if user_signed_in? %>  

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>

              <ul class="dropdown-menu">          
                <li><%= link_to 'Profile', user_path(current_user) %></li>
                <li><%= link_to 'User Settings', edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul> 
            </li>  
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>     
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>